jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET:}
  refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET:}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:36000} #10시간
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME:604800} #7일
  issuer: ${JWT_ISSUER:}

oauth:
  redirect-uri: ${REDIRECT_URL}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: https://bb-konkuk.shop/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: https://bb-konkuk.shop/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            provider: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
